applications/entry/urls.py
from django.urls import path
from . import views


app_name = "entry_app"

urlpatterns = [
    path('entry/list', views.EntryListView.as_view(),
         name='list'),
    path('entry/detail/<slug>', views.EntryDetailView.as_view(),
         name='detail'),
]

applications/home/urls.py
from django.urls import path
from . import views


app_name = "home_app"

urlpatterns = [
    path('', views.HomePageView.as_view(), name='index'),
    path('register-subscriber', views.SubscriberCreateView.as_view(),
         name='register_subscriber'),
    path('contact', views.ContactCreateView.as_view(),
         name='contact'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from applications.home.sitemap import EntrySitemap, Sitemap

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entry.urls')),
    re_path('', include('applications.favorite.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitemaps = {
    'site': Sitemap(
        [
            'home_app:index'
        ]
    ),
    'entry': EntrySitemap
}

urlpatterns_sitemap = [
    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    )
]

urlpatterns += urlpatterns_sitemap

applications/home/models.py
from django.db import models
from model_utils.models import TimeStampedModel


class Home(TimeStampedModel):
    title = models.CharField(max_length=30)
    description = models.TextField()
    about = models.CharField(max_length=50)
    is_published = models.BooleanField(default=True)
    about_text = models.TextField()
    contact_email = models.EmailField(blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return self.title


class Subscriber(TimeStampedModel):
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.email


class Contact(TimeStampedModel):
    name = models.CharField(max_length=60)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.name

applications/home/forms.py
from django import forms
from django.forms import widgets
from .models import Subscriber, Contact


class SubscriberForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        fields = ('email',)
        widgets = {
            'email': widgets.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'})
        }


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('__all__')

applications/home/views.py
from django.views.generic import TemplateView, CreateView
from applications.entry.models import Entry
from .models import Home
from .forms import SubscriberForm, ContactForm


class HomePageView(TemplateView):
    template_name = 'home/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['home'] = Home.objects.filter(
            is_published=True).latest('created')
        context['home_cover'] = Entry.objects.get_home_cover()
        context['home_entries'] = Entry.objects.get_home_entries()
        context['recent_entries'] = Entry.objects.get_recent_entries()

        context['form'] = SubscriberForm()

        return context


class SubscriberCreateView(CreateView):
    form_class = SubscriberForm
    success_url = '.'


class ContactCreateView(CreateView):
    form_class = ContactForm
    success_url = '.'

templates/home/base_home.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<link rel='stylesheet' href='{% static "css/style.css" %}'>
{% endblock %}

{% block js %}
{% endblock %}

templates/home/index.html
{% extends "home/base_home.html" %}
{% block title %}{{ home.title }}{% endblock %}
{% block description %}
<meta name="description" content="{{ home.description }}">
{% endblock %}
{% load static %}

{% block content %}

{% include "includes/header.html" %}

<div class="container mt-4">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <img src="{{ home_cover.image.url }}" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">
                        <a href="{% url 'entry_app:detail' home_cover.slug %}">{{home_cover.title}}</a>
                    </h5>
                    <p class="card-text">{{ home_cover.summary }}</p>
                    <a href="{% url 'entry_app:detail' home_cover.slug %}" class="btn btn-primary">Read full entry</a>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="row row-cols-1 row-cols-md-2 g-4">
                {% for home_entry in home_entries %}
                <div class="col">
                    <div class="card">
                        {% if home_entry.image %}
                        <img src="{{ home_entry.image.url }}" class="card-img-top entry-image">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">
                                <a href="{% url 'entry_app:detail' home_entry.slug %}">{{home_entry.title }}</a>
                            </h5>
                            <p class="card-text">{{ home_entry.summary | truncatechars:30 }}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="row mt-5">
        <div class="bg-light col-12 container p-3 w-75 text-secondary card border-black mb-3">
            <h4>{{ home.about }}</h4>
            <p>{{ home.about_text }}</p>
            <p>
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#subscribeModal">
                    Subscribe
                </button>
            </p>
            <div class="modal fade" id="subscribeModal" tabindex="-1" aria-labelledby="subscribeModalLabel"
                aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <form method="post" action="{% url 'home_app:register_subscriber' %}">
                            {% csrf_token %}
                            <div class="modal-header">
                                <h5 class="modal-title" id="subscribeModalLabel">Add you email</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                {{ form.email }}
                            </div>
                            <div class="modal-footer">
                                <button type="submit " class="btn btn-primary">Subscribe</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <h2 class="mt-4">Recent Articles</h2>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for recent_entry in recent_entries %}
        <div class="col">
            <div class="card">
                {% if recent_entry.image %}
                <a href=""><img src="{{ recent_entry.image.url }}" class="card-img-top entry-image"></a>
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">
                        <a href="{% url 'entry_app:detail' recent_entry.slug %}">{{recent_entry.title }}</a>
                    </h5>
                    <p class="card-text">{{ recent_entry.summary | truncatechars:30 }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% include "includes/footer.html" %}
{% endblock %}