applications/entry/urls.py
from django.urls import path
from . import views


app_name = "entry_app"

urlpatterns = [
    path('entry/list', views.EntryListView.as_view(),
         name='list'),
    path('entry/detail/<slug>', views.EntryDetailView.as_view(),
         name='detail'),
]

applications/favorite/urls.py
from django.urls import path
from . import views


app_name = "favorite_app"

urlpatterns = [
    path('favorite/add/<pk>', views.AddFavoriteView.as_view(), name='add'),
    path('favorite/delete/<pk>', views.DeleteFavoriteView.as_view(), name='delete'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from applications.home.sitemap import EntrySitemap, Sitemap

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entry.urls')),
    re_path('', include('applications.favorite.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitemaps = {
    'site': Sitemap(
        [
            'home_app:index'
        ]
    ),
    'entry': EntrySitemap
}

urlpatterns_sitemap = [
    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    )
]

urlpatterns += urlpatterns_sitemap

applications/entry/models.py
from datetime import timedelta, datetime
from django.db import models
from django.conf import settings
from django.urls import reverse_lazy
from django.template.defaultfilters import slugify
from model_utils.models import TimeStampedModel
from ckeditor_uploader.fields import RichTextUploadingField
from .managers import EntryManager


class Category(TimeStampedModel):
    short_name = models.CharField(max_length=30, unique=True)
    name = models.CharField(max_length=30)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.short_name


class Tag(TimeStampedModel):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Entry(TimeStampedModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)
    title = models.CharField(max_length=200)
    summary = models.TextField()
    content = RichTextUploadingField()
    published = models.BooleanField(default=False)
    image = models.ImageField(upload_to='images/', blank=True)
    cover = models.BooleanField(default=False)
    in_home = models.BooleanField(default=False)
    slug = models.SlugField(max_length=300, editable=False)

    objects = EntryManager()

    class Meta:
        verbose_name_plural = "Entries"

    def __str__(self):
        return self.title

    def save(self):
        now = datetime.now()
        total_time = timedelta(
            hours=now.hour, minutes=now.minute, seconds=now.second)
        self.slug = slugify('%s %s' % (self.title, int(total_time.seconds)))
        super(Entry, self).save()

    def get_absolute_url(self):
        return reverse_lazy('entry_app:detail', kwargs={'slug': self.slug})

applications/entry/views.py
from unicodedata import category
from django.views.generic import ListView, DetailView
from .models import Entry, Category


class EntryListView(ListView):
    model = Entry
    template_name = 'entry/list.html'
    context_object_name = 'entries'
    paginate_by = 5

    def get_queryset(self):
        title = self.request.GET.get('title', '')
        category = self.request.GET.get('category', '')
        return Entry.objects.search_entries(title, category)

    def get_context_data(self, **kwargs):
        context = super(EntryListView, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all().order_by('name')
        return context


class EntryDetailView(DetailView):
    model = Entry
    template_name = 'entry/detail.html'

    def get_context_data(self, **kwargs):
        context = super(EntryDetailView, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all().order_by('name')
        return context

templates/entry/base_entry.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<link rel='stylesheet' href='{% static "css/style.css" %}'>
{% endblock %}

{% block js %}
{% endblock %}

templates/entry/detail.html
{% extends "entry/base_entry.html" %}
{% block title %}{{ entry.title }}{% endblock %}
{% block description %}
<meta name="description" content="{{ entry.summary }}">
{% endblock %}
{% block tags %}
<meta name="keywords" content="
{% for tag in entry.tags.all  %}
    {{ tag.name }},
{% endfor %}
">
{% endblock %}
{% load static %}

{% block content %}

{% include "includes/header.html" %}

<div class="container">
    <h1>{{ entry.title }}</h1>
    <div class="row">
        <div class="col-md-9">
            <div class="alert alert-primary">
                <h4 class="alert-heading">Summary</h4>
                <p>
                    {{ entry.summary }}
                </p>
            </div>
            <p>
                {{ entry.content | safe }}
            </p>
        </div>
        <div class="col-md-3">
            <div class="card">
                {% if entry.image %}
                <img src="{{ entry.image.url }}" class="card-img-top entry-image">
                {% endif %}
                <form method="post" action="{% url 'favorite_app:add' entry.id %}"
                    class="card-body d-flex justify-content-center">
                    {% csrf_token %}
                    <button class="btn btn-primary" type="submit">Add to favorites</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% include "includes/footer.html" %}
{% endblock %}

templates/entry/list.html
{% extends "entry/base_entry.html" %}
{% block title %}Entries{% endblock %}
{% load static %}

{% block content %}

{% include "includes/header.html" %}

<div class="container">
    <div class="row my-3">
        <div class="col-md-9">
            <form method="get">
                {% csrf_token %}
                <div class="input-group">
                    <input type="text" id="title" name="title" class="form-control" placeholder="Search">
                    <button class="btn btn-primary" type="submit">Search</button>
                </div>
            </form>
            <div class="row row-cols-1 row-cols-md-3 g-4 mt-2">
                {% for entry in entries %}
                <div class="col">
                    <div class="card">
                        {% if entry.image %}
                        <img src="{{ entry.image.url }}" class="card-img-top entry-image">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">
                                <a href="{% url 'entry_app:detail' entry.slug %}">{{ entry.title }}</a>
                            </h5>
                            <p class="card-text">{{ entry.summary | truncatechars:30 }}</p>
                        </div>
                    </div>
                </div>
                {% empty %}
                <h5 class="text-danger">No entries found</h5>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-3">
            <h2>Categories</h2>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <a href="{% url 'entry_app:list' %}">All</a>
                </li>
                {% for category in categories %}
                <li class="list-group-item">
                    <a href="?category={{ category.id }}">{{ category.short_name }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="row">
        {% if is_paginated %}
        <nav aria-label="Pagination" class="col-md-3">
            <ul class="pagination justify-content-start">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number}}">Previous</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link">Previous</a>
                </li>
                {% endif %} {% for page in paginator.page_range %} {% ifequal page page_obj.number %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="?page={{ page }}">{{ page }}</a>
                </li>
                {% else %}
                <li class="page-item" aria-current="page">
                    <a class="page-link" href="?page={{ page }}">{{ page }}</a>
                </li>
                {% endifequal %} {% endfor %} {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number}}">Next</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link">Next</a>
                </li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
    </div>
</div>

{% include "includes/footer.html" %}
{% endblock %}