applications/entry/urls.py
from django.urls import path
from . import views


app_name = "entry_app"

urlpatterns = [
    path('entry/list', views.EntryListView.as_view(),
         name='list'),
    path('entry/detail/<slug>', views.EntryDetailView.as_view(),
         name='detail'),
]

applications/home/urls.py
from django.urls import path
from . import views


app_name = "home_app"

urlpatterns = [
    path('', views.HomePageView.as_view(), name='index'),
    path('register-subscriber', views.SubscriberCreateView.as_view(),
         name='register_subscriber'),
    path('contact', views.ContactCreateView.as_view(),
         name='contact'),
]

applications/users/urls.py
from django.urls import path
from . import views


app_name = "users_app"

urlpatterns = [
    path("users/panel", views.PanelView.as_view(), name="panel"),
    path("users/register", views.UserRegisterView.as_view(), name="register"),
    path("users/login", views.LoginView.as_view(), name="login"),
    path("users/logout", views.LogOutView.as_view(), name="logout"),
    path(
        "users/update_password",
        views.UpdatePasswordView.as_view(),
        name="update_password",
    ),
    path("users/verify/<pk>/", views.CodeVerificationView.as_view(), name="verify"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from applications.home.sitemap import EntrySitemap, Sitemap

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entry.urls')),
    re_path('', include('applications.favorite.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitemaps = {
    'site': Sitemap(
        [
            'home_app:index'
        ]
    ),
    'entry': EntrySitemap
}

urlpatterns_sitemap = [
    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    )
]

urlpatterns += urlpatterns_sitemap

applications/home/models.py
from django.db import models
from model_utils.models import TimeStampedModel


class Home(TimeStampedModel):
    title = models.CharField(max_length=30)
    description = models.TextField()
    about = models.CharField(max_length=50)
    is_published = models.BooleanField(default=True)
    about_text = models.TextField()
    contact_email = models.EmailField(blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return self.title


class Subscriber(TimeStampedModel):
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.email


class Contact(TimeStampedModel):
    name = models.CharField(max_length=60)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.name

templates/includes/footer.html
<section id="contact" class="bg-light py-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <h3>Get In touch</h3>
                <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit, maiores.</p>
                <form method="post" action="{% url 'home_app:contact' %}">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <span class="input-group-text"><i class="fas fa-user"></i></span>
                        <input type="text" class="form-control" placeholder="Name" id="id_name" name="name">
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text"><i class="fas fa-envelope"></i></span>
                        <input type="email" class="form-control" placeholder="Email" id="id_email" name="email">
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text"><i class="fas fa-pencil-alt"></i></span>
                        <textarea class="form-control" placeholder="Message" rows="5" id="id_message"
                            name="message"></textarea>
                    </div>
                    <div class="d-grid gap-2">
                        <button type="submit" class="btn btn-primary btn-lg">Send</button>
                    </div>
                </form>
            </div>
        </div>
        <p class="mt-2 lead">
            Another contact forms:
        </p>
        {% if contact_email %}
        <p class="lead">{{ contact_email }}</p>
        {% endif %}

        {% if phone %}
        <p class="lead">{{ phone }}</p>
        {% endif %}
    </div>
</section>

templates/includes/header.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
    <div class="container-fluid">
        <a class="navbar-brand text-primary" href="/">Some of my Philosophy</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarSupportedContent">
            <div class="d-flex">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'entry_app:list' %}">Blog</a>
                    </li>
                </ul>
                {% if user.is_authenticated == False %}
                <a class="btn btn-outline-secondary mx-3" href="{% url 'users_app:login' %}">
                    Login
                </a>
                {% else %}
                <a class="btn btn-success mx-3" href="{% url 'users_app:panel' %}">
                    Profile
                </a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>