applications/entry/urls.py
from django.urls import path
from . import views


app_name = "entry_app"

urlpatterns = [
    path('entry/list', views.EntryListView.as_view(),
         name='list'),
    path('entry/detail/<slug>', views.EntryDetailView.as_view(),
         name='detail'),
]

applications/favorite/urls.py
from django.urls import path
from . import views


app_name = "favorite_app"

urlpatterns = [
    path('favorite/add/<pk>', views.AddFavoriteView.as_view(), name='add'),
    path('favorite/delete/<pk>', views.DeleteFavoriteView.as_view(), name='delete'),
]

applications/users/urls.py
from django.urls import path
from . import views


app_name = "users_app"

urlpatterns = [
    path("users/panel", views.PanelView.as_view(), name="panel"),
    path("users/register", views.UserRegisterView.as_view(), name="register"),
    path("users/login", views.LoginView.as_view(), name="login"),
    path("users/logout", views.LogOutView.as_view(), name="logout"),
    path(
        "users/update_password",
        views.UpdatePasswordView.as_view(),
        name="update_password",
    ),
    path("users/verify/<pk>/", views.CodeVerificationView.as_view(), name="verify"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from applications.home.sitemap import EntrySitemap, Sitemap

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entry.urls')),
    re_path('', include('applications.favorite.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitemaps = {
    'site': Sitemap(
        [
            'home_app:index'
        ]
    ),
    'entry': EntrySitemap
}

urlpatterns_sitemap = [
    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    )
]

urlpatterns += urlpatterns_sitemap

applications/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    GENDER_CHOICES = (("M", "Male"), ("F", "Female"))

    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, blank=True)
    job_title = models.CharField(max_length=30, blank=True)
    gender = models.CharField(
        max_length=1, choices=(GENDER_CHOICES), blank=True)
    register_code = models.CharField(max_length=6, blank=True)
    birth_date = models.DateField(blank=True, null=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name"]

    objects = UserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.first_name + " " + self.last_name

applications/users/forms.py
from django import forms
from django.contrib.auth import authenticate
from .models import User


class UserRegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name',
                  'job_title', 'birth_date')

    email = forms.CharField(
        required=True,
        widget=forms.EmailInput(
            attrs={'class': 'form-control form-control-lg', 'placeholder': 'Email'})
    )

    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control form-control-lg', 'placeholder': 'First name'})
    )

    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control form-control-lg", 'placeholder': 'Last name'})
    )

    job_title = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control form-control-lg", 'placeholder': 'Job title'})
    )

    gender = forms.ChoiceField(
        choices=User.GENDER_CHOICES,
        widget=forms.Select(
            attrs={"class": "form-control form-control-lg"})
    )

    birth_date = forms.DateField(
        widget=forms.DateInput(
            format=('%Y/%m/%d'), attrs={'class': 'form-control form-control-lg', 'type': 'date'}))

    password = forms.CharField(
        label="Password",
        required=True,
        widget=forms.PasswordInput(
            attrs={"class": "form-control form-control-lg", 'placeholder': 'Password'}),
    )

    repassword = forms.CharField(
        label="Repeat password",
        required=True,
        widget=forms.PasswordInput(
            attrs={"class": "form-control form-control-lg", 'placeholder': 'Repeat password'}),
    )

    def clean_repassword(self):
        password = self.cleaned_data.get("password")
        repassword = self.cleaned_data.get("repassword")
        if len(password) < 5:
            self.add_error(
                "password", "Password length must be greater than 5 characters"
            )
            return

        if password != repassword:
            self.add_error(
                "repassword", "Password and repeat password are not the same"
            )

    class Meta:
        model = User
        fields = ("email", "first_name", "last_name", "gender")


class LoginForm(forms.Form):
    email = forms.CharField(
        label="email",
        required=True,
        widget=forms.TextInput(
            attrs={"class": "form-control form-control-lg",
                   'placeholder': 'Email'}
        )
    )

    password = forms.CharField(
        label="Password",
        required=True,
        widget=forms.PasswordInput(
            attrs={"class": "form-control form-control-lg",
                   'placeholder': 'Password'}
        )
    )

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        if not authenticate(email=email, password=password):
            raise forms.ValidationError("Email or password is incorrect")
        return self.cleaned_data


class UpdatePasswordForm(forms.Form):
    password = forms.CharField(
        label="Current password",
        required=True,
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
    )

    new_password = forms.CharField(
        label="New password",
        required=True,
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
    )


class EmailVerificationForm(forms.Form):
    code = forms.CharField(
        label="Verification code",
        required=True,
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )

    def __init__(self, pk, *args, **kwargs):
        self.id = pk
        super(EmailVerificationForm, self).__init__(*args, **kwargs)

    def clean_code(self):
        code = self.cleaned_data.get("code")

        if len(code) != 6:
            raise forms.ValidationError(
                "Verification code length is incorrect")

        if not User.objects.code_validation(self.id, code):
            raise forms.ValidationError("Verification code is incorrect")

        return code

applications/users/views.py
from django.views.generic import View, ListView
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login, logout
from django.core.mail import send_mail
from .forms import (
    UserRegisterForm,
    LoginForm,
    UpdatePasswordForm,
    EmailVerificationForm,
)
from .models import User
from .functions import code_generator


class UserRegisterView(FormView):
    template_name = "users/register.html"
    form_class = UserRegisterForm
    success_url = reverse_lazy("users_app:panel")

    def form_valid(self, form):
        register_code = code_generator()
        user = User.objects.create_user(
            form.cleaned_data["email"],
            form.cleaned_data["password"],
            first_name=form.cleaned_data["first_name"],
            last_name=form.cleaned_data["last_name"],
            gender=form.cleaned_data["gender"],
            register_code=register_code,
        )

        subject = "Confirmation email"
        message = f"Verification code: {register_code}"
        sender = "eliashhtorres@gmail.com"
        send_mail(subject, message, sender, [form.cleaned_data["email"]])

        return redirect(reverse("users_app:verify", kwargs={"pk": user.id}))


class LoginView(FormView):
    template_name = "users/login.html"
    form_class = LoginForm
    success_url = reverse_lazy("users_app:panel")

    def form_valid(self, form):
        user = authenticate(
            email=form.cleaned_data["email"],
            password=form.cleaned_data["password"],
        )
        login(self.request, user)
        return super(LoginView, self).form_valid(form)


class PanelView(LoginRequiredMixin, ListView):
    template_name = "users/panel.html"
    context_object_name = "user_favorites"
    login_url = reverse_lazy("users_app:login")

    def get_queryset(self):
        return User.objects.get_user_favorites(self.request.user)


class LogOutView(View):
    def get(self, request):
        logout(request)
        return redirect(reverse("users_app:login"))


class UpdatePasswordView(LoginRequiredMixin, FormView):
    login_url = "users_app:login"
    template_name = "users/update_password.html"
    form_class = UpdatePasswordForm
    success_url = reverse_lazy("users_app:login")

    def form_valid(self, form):
        user = self.request.user
        auth = authenticate(
            username=user.username,
            password=form.cleaned_data["password"],
        )
        if auth:
            user.set_password(form.cleaned_data["new_password"])
            user.save()

        logout(self.request)
        return super(UpdatePasswordView, self).form_valid(form)


class CodeVerificationView(FormView):
    template_name = "users/code_verification.html"
    form_class = EmailVerificationForm
    success_url = reverse_lazy("users_app:login")

    def get_form_kwargs(self):
        kwargs = super(CodeVerificationView, self).get_form_kwargs()
        kwargs.update({"pk": self.kwargs["pk"]})
        return kwargs

    def form_valid(self, form):
        User.objects.filter(id=self.kwargs["pk"]).update(is_active=True)
        return super(CodeVerificationView, self).form_valid(form)

templates/users/base_users.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<link rel='stylesheet' href='{% static "css/style.css" %}'>
{% endblock %}

{% block js %}
{% endblock %}

templates/users/login.html
{% extends "users/base_users.html" %}
{% block title %}Login{% endblock %}

{% load static %}

{% block content %}

{% include "includes/header.html" %}

<div class="container mt-4 d-flex justify-content-center text-light">
    <div class="col-lg-6">
        <div class="card bg-primary text-center card-form">
            <div class="card-body">
                <h3>User Access</h3>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3">
                        {{ form.email }}
                    </div>
                    <div class="mb-3">
                        {{ form.password }}
                    </div>
                    <div class="mb-3 d-grid gap-2">
                        <button type="submit" class="btn btn-outline-light btn-block btn-lg">Login</button>
                        <a class="btn btn-outline-light btn-block btn-lg" href="{% url 'users_app:register' %}">
                            Register
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/users/panel.html
{% extends "users/base_users.html" %}
{% block title %}User panel{% endblock %}

{% load static %}

{% block content %}

{% include "includes/header.html" %}

<div class="container mt-4">
    <div class="row">
        <div class="col-md-4 callout">
            <h5>{{ user.first_name }}{{ user.last_name }}</h5>
            <p>{{ user }} - {{ user.job_title }} - {{ user.birth_date }}</p>
            <a href="">Edit profile</a>
            <br>
            <a href="{% url 'users_app:logout' %}" class="text-danger">Logout</a>
        </div>
        <div class="col-md-8">
            {% for user_favorite in user_favorites %}
            <div class="card mb-3">
                <div class="row g-0">
                    <div class="col-md-4">
                        {{ user_favorite }}
                        {% if user_favorite.entry.image %}
                        <img src="{{ user_favorite.entry.image.url }}" class="img-fluid rounded-start profile-image">
                        {% endif %}
                    </div>
                    <div class="col-md-8">
                        <form class="card-body" method="post" action="{% url 'favorite_app:delete' user_favorite.id %}">
                            {% csrf_token %}
                            <h5 class="card-title">{{ user_favorite.entry.title }}</h5>
                            <p class="card-text">{{ user_favorite.entry.summary }}</p>
                            <a class="btn btn-info text-light"
                                href="{% url 'entry_app:detail' user_favorite.entry.slug %}">
                                See article
                            </a>
                            <button type="submit" class="btn btn-danger text-light">Delete from favorites</button>
                        </form>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

templates/users/register.html
{% extends "users/base_users.html" %}
{% block title %}Register{% endblock %}

{% load static %}

{% block content %}

{% include "includes/header.html" %}

<div class="container mt-4 d-flex justify-content-center text-light">
    <div class="col-lg-8">
        <div class="card bg-primary text-center card-form">
            <div class="card-body">
                <h3>Sign Up Today</h3>
                <p>Please fill out this form to register</p>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3">
                        {{ form.email }}
                    </div>
                    <div class="row mb-3 g-3">
                        <div class="col-6">
                            {{ form.first_name }}
                        </div>
                        <div class="col-6">
                            {{ form.last_name }}
                        </div>
                    </div>
                    <div class="mb-3">
                        {{ form.job_title }}
                    </div>
                    <div class="row mb-3 g-3">
                        <div class="col-6">
                            <label for="gender">Gender</label>
                            {{ form.gender }}
                        </div>
                        <div class="col-6">
                            <label for="birth_date">Birth date</label>
                            {{ form.birth_date }}
                        </div>
                    </div>
                    <div class="mb-3">
                        {{ form.password }}
                        {% for error in form.password.errors %}
                        <div class="alert alert-danger mt-2">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <div class="mb-3">
                        {{ form.repassword }}
                        {% for error in form.repassword.errors %}
                        <div class="alert alert-danger mt-2">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <div class="mb-3 d-grid gap-2">
                        <button type="submit" class="btn btn-outline-light btn-block btn-lg mt-2">Register</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}